import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0F0F7',
  },
  topBar: {
    paddingTop: 40,
    paddingHorizontal: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#8257E5',
  },
  topBarName: {
    fontFamily: 'Archivo_400Regular',
    fontSize: 14,
    lineHeight: 15,
    color: '#D4C2FF',
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleHeader: {
    fontFamily: 'Archivo_700Bold',
    color: '#FFF',
    fontSize: 24,
    lineHeight: 32,
    marginTop: 41,
    marginBottom: 16,
  },
  subTitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    lineHeight: 24,
    color: '#D4C2FF',
  },
  header: {
    paddingHorizontal: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#8257E5',
    paddingBottom: 80,
  },
  card: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    marginHorizontal: 16,
    marginTop: -30,
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  avatarContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    marginRight: 15,
  },
  name: {
    fontFamily: 'Archivo_700Bold',
    color: '#32264D',
    fontSize: 20,
    lineHeight: 25,
  },
  subject: {
    marginTop: 4,
    color: '#6A6180',
    fontSize: 12,
    lineHeight: 26,
    fontFamily: 'Poppins_400Regular',
  },
  label: {
    color: '#9C98A6',
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    lineHeight: 22,
  },
  input: {
    height: 54,
    backgroundColor: '#FAFAFC',
    borderRadius: 8,
    borderColor: '#E6E6F0',
    borderStyle: 'solid',
    borderWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 16,
  },
  textArea: {
    height: 295,
    backgroundColor: '#FAFAFC',
    borderRadius: 8,
    borderColor: '#E6E6F0',
    borderStyle: 'solid',
    borderWidth: 1,
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 16,
    justifyContent: 'flex-start',
  },
  titleAndButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  addButton: {
  },
  addButtonText: {
    fontFamily: 'Archivo_600SemiBold',
    fontSize: 14,
    lineHeight: 26,
    color: '#8257E5',
  },
  fieldset: {},
  inputGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inputBlock: {
    width: '48%',
  },
  title: {
    fontFamily: 'Archivo_600SemiBold',
    fontSize: 18,
    lineHeight: 30,
    color: '#32264D',
    borderBottomColor: '#E6E6F0',
    borderBottomWidth: 1,
    borderStyle: 'solid',
    paddingBottom: 10,
    marginVertical: 30,
  },
  footerSeparator: {
    alignItems: 'center'
  },
  line: {
    width: '100%',
    borderStyle: 'solid',
    borderBottomColor: '#E6E6F0',
    borderWidth: .5,
    marginTop: 16,
  },
  deleteLineButton: {
    backgroundColor: '#FFF',
    width: 120,
    height: 30,
    marginTop: -12,
    alignItems: 'center',
  },
  deleteLineButtonText: {
    fontFamily: 'Archivo_600SemiBold',
    fontSize: 12,
    lineHeight: 20,
    color: '#E33D3D',
  },
  footer: {
    height: 160,
    backgroundColor: '#FAFAFC',
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    paddingHorizontal: 40,
    marginHorizontal: 16,
    marginBottom: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerButton: {
    width: 293,
    height: 56,
    borderRadius: 8,
    backgroundColor: '#04D361',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerButtonText: {
    fontFamily: 'Archivo_600SemiBold',
    fontSize: 16,
    lineHeight: 26,
    color: '#FFF',
  },
  footerAlert: {
    flexDirection: 'row',
    marginVertical: 24,
  },
  footerAlertTextContainer: {
    marginLeft: 16,
    marginRight: 80,
  },
  footerAlertTitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    lineHeight: 20,
    color: '#8257E5',
  },
  footerAlertMessage: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12,
    lineHeight: 20,
    color: '#A0A0B3',
  },

});

export default styles;
